(define (start-segment line) (car line))
(define (end-segment line) (cdr line))
(define (make-segment start end)
  (cons start end))
(define (make-point x y)
  (cons x y))
(define (x-point point)
  (car point))
(define (y-point point)
  (cdr point))
(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))
(define (average x y) (/ (+ x y) 2))
(define (midpoint-segment line)
  (define start-point (start-segment line))
  (define end-point (end-segment line))
  (make-point
   (average (x-point start-point) (x-point end-point))
   (average (y-point start-point) (y-point end-point))))
(define start (make-point 0 0))
(define end (make-point 2 2))
(define line (make-segment start end))
(print-point (midpoint-segment line))
;(1,1)
